### ISSUE TITLE
Feature request: Canadian currency conversion

### ISSUE THREAD

**Issue by glaverty** [isonium/CloudAtCost-Wallet#5]
I'm trying to use this to do my taxes - much better than the copy paste I was trying to do!.  It would be convenience if the google doc it also handled the USD->CAD currency conversion, and displayed CAD as another column anywhere we display USD.

**Comment by mrd0n** [comment]
Hi - One option is to add this formula to Column M, Row 3 in the google sheet (and copy down):
`=index(GOOGLEFINANCE("Currency:USDCAD", "price",J3,1),2,2)`

This will use the google finance api to lookup the Current Conversion on each day from USD to CAD

**Comment by mrd0n** [comment]
I updated the Google Sheet Template to include CAD prices

**Comment by glaverty** [comment]
Nice!  That's perfect, thank you very much!!!
